before_script:
  - "ruby --version"
  - "bundle exec rake test_app"
script: "bundle exec rake"
branches:
  only:
    - master
    - 2-1-stable
rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
env:
  - RAILS=3.2.13
matrix:
  allow_failures:
    - rvm: 2.0.0
